services:
  chaos-engine:
    build: ../chaos-engine
    container_name: chaos-engine
    depends_on:
    - prometheus
    environment:
    - LOKI_URL=http://loki:3100/loki/api/v1/push
    - SERVICE_NAME=chaos-engine
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  dashboard-backend:
    build: ../dashboard/backend
    container_name: dashboard-backend
    depends_on:
    - prometheus
    environment:
    - PROMETHEUS_URL=http://prometheus:9090
    - LOKI_URL=http://loki:3100/loki/api/v1/push
    - SERVICE_NAME=dashboard-backend
  dashboard-frontend:
    build: ../dashboard/frontend
    container_name: dashboard-frontend
    depends_on:
    - dashboard-backend
  grafana:
    container_name: grafana
    depends_on:
    - prometheus
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:10.0.0
    ports:
    - 3000:3000
    volumes:
    - ./infrastructure/grafana/provisioning/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    - ./infrastructure/grafana/provisioning/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    - ./infrastructure/grafana/dashboards/crashboard.json:/etc/grafana/provisioning/dashboards/crashboard.json
  loki:
    command: -config.file=/etc/loki/loki-config.yaml
    container_name: loki
    image: grafana/loki:2.8.2
    ports:
    - 3100:3100
    volumes:
    - ./infrastructure/loki/loki-config.yaml:/etc/loki/loki-config.yaml
  metric-collector:
    build: ../services/metric-collector
    container_name: metric-collector
    depends_on:
    - prometheus
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  notif-service:
    entrypoint:
    - sh
    - -c
    - pip install -e /crashboard-sdk && uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
    - ../crashboard-sdk:/crashboard-sdk
  order-service:
    entrypoint:
    - sh
    - -c
    - pip install -e /crashboard-sdk && uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
    - ../crashboard-sdk:/crashboard-sdk
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    container_name: prometheus
    image: prom/prometheus:v2.45.0
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  user-service-1:
    entrypoint:
    - sh
    - -c
    - pip install -e /crashboard-sdk && uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
    - ../crashboard-sdk:/crashboard-sdk
  user-service-2:
    entrypoint:
    - sh
    - -c
    - pip install -e /crashboard-sdk && uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
    - ../crashboard-sdk:/crashboard-sdk
version: '3.8'
